import localFont from "next/font/local";
import "./globals.css";
import { Appbar,Footer } from '@/Components'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col `}
      >
        <Appbar/>
        <main className="flex-grow min-w-screen-4xl  w-full max-h-full min-h-screen mx-auto">
        {children}
        </main>
        <Footer/>
      </body>
      {/* <script src="html2pdf.bundle.min.js"></script> */}
    </html>
  );
}
